version: '3.8'

services:
  # frontend:
  #   image: frontend:latest
  #   container_name: frontend_container
  #   ports:
  #     - "3000:3000"
  # backend:
  #   image: backend:latest
  #   container_name: backend_container
  #   environment:
  #     SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/mydatabase
  #     SPRING_DATASOURCE_USERNAME: myuser
  #     SPRING_DATASOURCE_PASSWORD: mypassword
  #     SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.mariadb.jdbc.Driver
  #     SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop
  #   ports:
  #     - "8090:8090"
  #   networks:
  #     - app_network
  #   depends_on:
  #     - db
  db:
    image: mariadb
    container_name: mariadb_container
    # restart: always
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql
      # - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MARIADB_DATABASE: vta_database
      MARIADB_ROOT_PASSWORD: myrootpassword
      MARIADB_USER: myuser
      MARIADB_PASSWORD: mypassword
      MYSQL_RANDOM_ROOT_PASSWORD: "false"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mariadb-data:
    driver: local
