name: Check Pom Version on PR to master

on:
  pull_request:
    branches:
      - master
    paths:
      - "backend/src/**"

jobs:
  check-pom-version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      
      - name: Check Pom Version
        run: >
          git fetch;
          git branch -a;

          LOCAL_VERSION=$(grep -o '^[ \t]<version>[^<]*</version>'  backend/pom.xml | sed 's/*<version>//;s/<\/version>//' | head -1);
          echo "Local version: $LOCAL_VERSION";

          git fetch origin master;
          git checkout origin/master -- backend/pom.xml;

          REMOTE_VERSION=$(grep -o '^[ \t]<version>[^<]*</version>'  backend/pom.xml | sed 's/*<version>//;s/<\/version>//' | head -1);
          echo "Remote version: $REMOTE_VERSION";

          if [ "$REMOTE_VERSION" == "$LOCAL_VERSION" ]; then
            echo "::error::The version in pom.xml is the same as the one on master. Please update the version in your pull request.";
            exit 1;
          fi
