name: Check version in pom.xml

on:
  pull_request:
    branches:
      - master
      
jobs:
  check-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Check pom.xml version
      run: |
        if [[ $(git diff --name-only master $GITHUB_HEAD_REF | grep -E "^pom.xml$|^backend/src/") ]]; then
          if [[ $(mvn help:evaluate -Dexpression=project.version -q -DforceStdout) == $(git show master:pom.xml | mvn help:evaluate -Dexpression=project.version -q -DforceStdout) ]]; then
            echo "The pom.xml version is already in master. Please update the version and try again."
            exit 1
          fi
        fi
