name: Image Vulnerability Scan

on:
  pull_request:
    branches:
      - master
    paths:
      - "frontend/**"

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        working-directory: frontend
        run: npm install

      - name: Build app
        env:
          CI: false
        working-directory: frontend
        run: npm run build

      - name: Build and tag Docker image
        working-directory: frontend
        run: |
          docker build -t frontend:${{ github.sha }} .

      - name: Run vulnerability scan
        run: |
          docker pull aquasec/trivy
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd):/root/ --workdir /root/ aquasec/trivy image --exit-code 1 --severity CRITICAL "frontend:${{ github.sha }}"
