name: Image Vulnerability Scan

on:
    pull_request:
      branches:
        - master
      paths:
        - "backend/**"

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "adopt"

      - name: Build Spring Boot app
        working-directory: backend
        run: |
          ./mvnw -B clean package -DskipTests -Dmaven.verbose=false

      - name: Build and tag Docker image
        working-directory: backend
        run: |
          docker build -t backend:${{ github.sha }} .

      - name: Run vulnerability scan
        run: |
          docker pull aquasec/trivy
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd):/root/ --workdir /root/ aquasec/trivy image --exit-code 1 --severity CRITICAL "backend:${{ github.sha }}"
