name: Image Vulnerability Scan

on:
  pull_request:
    branches:
      - master
    paths:
      - "frontend/**"

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and tag Docker image
        run: |
          docker build -t backend:${{ github.sha }} .

      - name: Run vulnerability scan
        run: |
          docker pull aquasec/trivy
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd):/root/ --workdir /root/ aquasec/trivy --exit-code 1 backend:${{ github.sha }}
